---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 3 if not present
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false

    - name: Install Python 3 PIP (if necessary)
      ansible.builtin.apt:
        name: python3-pip
        state: present
