# - hosts: production
#   become: true
#   vars:
#     wp_version: 5.7.1
#     wp_webserver: nginx
#     wp_mysql_db: "wordpress"
#     wp_mysql_user: "datascientest"
#     wp_mysql_password: "mysql_pass"
#     wp_admin_email: "nawfal@soschmall.fr"
#     wp_sitename: "html"
#     wp_install_dir: "/var/www/html"
#   roles:
#     - wordpress
#     - mysql


---
- name: Setup Nginx
  hosts: production_nginx
  become: true
  vars:
    wp_sitename: "demo.com"
    wp_install_dir: "/var/www/demo.com"
  roles:
    - nginx

- name: Setup MySQL
  hosts: production_mysql
  become: true
  roles:
    - mysql

- name: Setup WordPress
  hosts: production_wordpress
  become: true
  vars:
    wp_version: 5.7.1
    wp_webserver: nginx
    wp_mysql_db: "wordpress"
    wp_mysql_user: "datascientest"
    wp_mysql_password: "mysql_pass"
    wp_admin_email: "nawfal@soschmall.fr"
    wp_sitename: "demo.com"
    wp_install_dir: "/var/www/demo.com"
  roles:
    - wordpress
    